### ISSUE TITLE
Env vars get lost after setting them during startup

### ISSUE THREAD

**Issue by booooza** [cloudfoundry-community/vcap-squash#4]
Hey Josh, great script and actually exactly what I was looking for. Have you recently tested if this still works for you? In my environment I see that the script `.profile.d/setenv.sh` actually gets run as pre-runtime hook at the startup of the php buildpack (v4.3.69) and it also sets the env variables with `eval $(./vcap-squash)` (I can use them during the same script) but after startup of the app they are gone again. Any idea?

**Comment by joshq00** [comment]
Hi @booooza, it does still work for me. If you output the `ENV` from your application to logs at startup, what do you see? Is it what you expect?
