### ISSUE TITLE
Thanks for this project

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/vcap-squash#5]
Just wanted to say thank you for making this project available.

I'm currently using it to do some interesting things with the telegraf binary && making service bindings available within `telegraf.conf` as environment variables.

https://github.com/aegershman/telegraf-on-cloudfoundry

That's all, just saying thanks

**Comment by joshq00** [comment]
You're welcome @aegershman! I'm glad it helped and thanks for the nice feedback
